apiVersion: apps/v1
kind: Deployment
metadata:
  name: teastore-persistence
  namespace: teastore
spec:
  replicas: 1
  selector:
    matchLabels:
      run: teastore-persistence
  template:
    metadata:
      labels:
        app: teastore
        run: teastore-persistence
    spec:
      containers:
        - name: teastore-persistence
          image: mennaelyamany/teastore-persistence:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: HOST_NAME
              value: "teastore-persistence"
            - name: REGISTRY_HOST
              value: "teastore-registry"
            - name: DB_HOST
              value: "teastore-db"
            - name: DB_PORT
              value: "3306"
          resources:
            requests:
              memory: "512Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: teastore-persistence
  namespace: teastore
  labels:
    app: teastore
    run: teastore-persistence
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    run: teastore-persistence
