apiVersion: apps/v1
kind: Deployment
metadata:
  name: teastore-image
  namespace: teastore
spec:
  replicas: 1
  selector:
    matchLabels:
      run: teastore-image
  template:
    metadata:
      labels:
        app: teastore
        run: teastore-image
    spec:
      containers:
        - name: teastore-image
          image: mennaelyamany/teastore-image:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: HOST_NAME
              value: "teastore-image"
            - name: REGISTRY_HOST
              value: "teastore-registry"
          resources:
            requests:
              memory: "1Gi"
              cpu: "200m"
            limits:
              memory: "2Gi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: teastore-image
  namespace: teastore
  labels:
    app: teastore
    run: teastore-image
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    run: teastore-image
